# Generated by Django 5.2.4 on 2025-07-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the blog post is currently active/visible'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(help_text="A unique slug for the URL, e.g., 'my-awesome-blog-post'", max_length=200, unique=True),
        ),
    ]
