# Generated by Django 5.2.3 on 2025-07-17 06:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_blogpost_is_active_alter_blogpost_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery_images/')),
                ('video', models.FileField(blank=True, help_text='Optional: Upload a video file instead of an image.', null=True, upload_to='gallery_videos/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(blank=True, help_text="e.g., 'Events', 'Projects', 'Community'", max_length=100, null=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='PartnershipInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('partnership_type', models.CharField(choices=[('Program Collaboration', 'Program Collaboration'), ('Funding/Sponsorship', 'Funding/Sponsorship'), ('Research', 'Research'), ('Advocacy', 'Advocacy'), ('Other', 'Other')], max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('inquiry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('New', 'New'), ('Reviewed', 'Reviewed'), ('Contacted', 'Contacted'), ('On Hold', 'On Hold'), ('Completed', 'Completed')], default='New', max_length=50)),
            ],
            options={
                'verbose_name': 'Partnership Inquiry',
                'verbose_name_plural': 'Partnership Inquiries',
                'ordering': ['-inquiry_date'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='team_members/')),
                ('linkedin_url', models.URLField(blank=True, max_length=500, null=True)),
                ('twitter_url', models.URLField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which team members appear')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('area_of_interest', models.CharField(choices=[('Community Outreach', 'Community Outreach'), ('Education & Training', 'Education & Training'), ('Administrative Support', 'Administrative Support'), ('Fundraising', 'Fundraising'), ('Other', 'Other')], max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Contacted', 'Contacted'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
            ],
            options={
                'verbose_name': 'Volunteer Application',
                'verbose_name_plural': 'Volunteer Applications',
                'ordering': ['-application_date'],
            },
        ),
    ]
