# Generated by Django 5.2.3 on 2025-07-20 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0005_category_blogpost_excerpt_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Assign a category (e.g., Program, Location) to this gallery item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_items', to='core_api.category'),
        ),
    ]
